Primeira avaliação - Feature/exercicio 1
Ricardonovais1/orion-bootcamp pull request #1
Opened 2023-10-10 00:58 UTC by Ricardonovais1

Realizei as 2 tarefas do exercício 1, que são:

a) Retornar o número de vogais de uma expressão com parâmetro de função

Criei a função countVowels, que:
1 - Inicializa em 0  avariável count;
2 - Declara o array de vogais vowels;
3 - Remove acentos da string dada como argumento da função;
4 - Transforma a string em um array, usando o método split();
5 - Transforma cada letra do array em minúscula;
6 - Incrementa em 1 a variável count para cada vogal (verificando se a letra pertence ao array vowels);
7 - Retorna o valor numérico referente à variável count.

b) Retornar o número de vogais usando valor inserido em um formulário

Uso a mesma função acima, pegando como argumento da função o input do usuário. 
Caso esteja vazio, exibo "Insira uma palavra ou frase".

2023-10-10 01:03 UTC, Ricardonovais1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Ricardo Novais] Exercício 01](https://trello.com/c/51VVgIcY/84-ricardo-novais-exerc%C3%ADcio-01)

2023-10-10 14:23 UTC, samuelcamilocosta requested changes

2023-10-10 14:23 UTC, samuelcamilocosta commented on package.json
> +    "typescript": "^5.2.2"
Te passar uma visão rápida das dependências

`"typescript": "^5.2.2"`
Aceita atualizações automáticas para versões compatíveis, mas não para grandes atualizações. (Atualizações de patch e menor versão são permitidas). Ou seja, 5.x.x, Ele não atualizaria para 6.0.0 ou maior.

`"typescript": "~5.2.2":`
Aceita apenas atualizações de patch dentro da mesma versão. (Correções de bugs são permitidas, mas não atualizações de menor ou maior versão). Ou seja, 5.2.x, ele não atualizaria para 5.3.0 ou maior.

`"typescript": "5.2.2":`
Fixa a versão em 5.2.2. (Não recebe automaticamente atualizações)

Então, recomendo sempre fixar as versões.

2023-10-10 14:23 UTC, samuelcamilocosta commented on src/exercicio-1.ts
> +  let vowels: string[] = ["a", "e", "i", "o", "u"];
Como a variável vowels não sofrerá nenhuma reatribuição, então é preferível utilizar const ao invés de let em sua declaração como boa prática. Isso impede a reatribuição acidental da variável, além de deixar claro para outros desenvolvedores que o valor não deve ser modificado ao longo do código.

2023-10-10 14:23 UTC, samuelcamilocosta commented on src/exercicio-1.ts
> +  let wordWithoutAccents: string = word.normalize('NFD').replace(/[\u0300-\u036f]/g, "");
a variável wordWithoutAccents também não possui reatribuição, sua declaração também pode ser como const

Foi uma boa adição o tratamento para acentos 👍

2023-10-10 14:23 UTC, samuelcamilocosta commented on src/exercicio-1.ts
> +let chosenWord: string = 'Tela';
Opte por utilizar const em vez de let em chosenWord, numberOfVowels e output

2023-10-10 14:23 UTC, samuelcamilocosta commented on src/exercicio-1.ts
> +const countVowels = (word: string): number => {
Utilize o TSDoc para documentar as funções/arrow-functions

https://tsdoc.org/

2023-10-10 15:37 UTC, Ricardonovais1 commented on src/exercicio-1.ts
> +const countVowels = (word: string): number => {
Fiz todas as demais correções, mas esta eu não compreendi. Pesquisei e no link que você me passou não encontrei nada sobre como posso melhorar esta documentação que fiz. Inclusive no Stackoverflow tem uma pergunta sobre isso sem resposta. Pode me auxiliar a como resolver isso?

2023-10-10 15:46 UTC, Ricardonovais1 commented on package.json
> +    "typescript": "^5.2.2"
Feito

2023-10-10 18:37 UTC, Ricardonovais1 reviewed
Samuel, eu fiz as alterações que você apontou, no commit 'Resolver mudanças solicitadas na PR'. Está faltando mais alguma coisa?

2023-10-10 20:53 UTC, samuelcamilocosta requested changes

2023-10-10 20:53 UTC, samuelcamilocosta commented on src/exercicio-1.ts
> +const btn: HTMLButtonElement = document.getElementById('result-btn') as HTMLButtonElement;
Por questões de legibilidade, é sempre bom evitarmos escrever no código typescript nomes resumidos, pois de acordo com que vai crescendo o código, torna mais dificil de identificação.

Então seria bom alterar o btn para button

2023-10-10 20:53 UTC, samuelcamilocosta commented on src/exercicio-1.ts
> +btn?.addEventListener('click', (e) => {
Adicione a tipagem do parâmetro "e".
Também vale a pena para deixar o parâmetro mais descritivo, alterá-lo para "event" em vez de "e".

2023-10-10 23:51 UTC, alan-rocha-newrizon requested changes

2023-10-10 23:51 UTC, alan-rocha-newrizon commented on src/exercicio-1.ts
> +const ResultButton: HTMLButtonElement = document.getElementById('result-btn') as HTMLButtonElement;
utilizar camelCase no nome de variaveis

2023-10-10 23:51 UTC, alan-rocha-newrizon commented on src/exercicio-1.ts
> +
remover espaço entre a documentação e a função

2023-10-11 12:58 UTC, samuelcamilocosta approved these changes

2023-10-11 13:04 UTC, merged