Feature/exercicio 3
Ricardonovais1/orion-bootcamp pull request #3
Opened 2023-10-11 19:08 UTC by Ricardonovais1

Nesta PR eu usei o paradigma funcional.

Na página implementei todos os exercícios, sendo que, para os itens do exercício 2
utilizei o paradigma funcional.

2023-10-11 19:10 UTC, Ricardonovais1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Ricardo Novais] Exercício-03](https://trello.com/c/TTOwbZbq/86-ricardo-novais-exerc%C3%ADcio-03)

2023-10-13 19:01 UTC, alan-rocha-newrizon requested changes

2023-10-13 19:01 UTC, alan-rocha-newrizon commented on src/exercicio-3-commits.ts
> +interface GithubCommit {
colocar a interface em um arquivo separado e importar para utilizar

2023-10-13 19:01 UTC, alan-rocha-newrizon commented on src/exercicio-3-commits.ts
> +function getCommitsGihubApi() {
faltou o tsdoc da função, e o tipo de retorno da função

2023-10-13 19:01 UTC, alan-rocha-newrizon commented on src/exercicio-3-commits.ts
> +function printCommit(commit: GithubCommit, count: number) {
faltou o tsdoc e o tipo de retorno da função

2023-10-13 19:01 UTC, alan-rocha-newrizon commented on src/exercicio-3.ts
> +  let scientist: Scientist | undefined = list.find(s => s.id === id);
variável com nome `s` não traz clareza do que se trata na leitura do código. utilizar um nome mais descritivo para a variável

2023-10-13 19:01 UTC, alan-rocha-newrizon commented on src/exercicio-3.ts
> +  let scientist: Scientist | undefined = list.find(s => s.id === id);
variável com nome `s` não traz clareza do que se trata na leitura do código. utilizar um nome mais descritivo para a variável

2023-10-13 19:01 UTC, alan-rocha-newrizon commented on src/exercicio-3.ts
> +  let scientist: Scientist | undefined = list.find(s => s.id === id);
variável com nome `s` não traz clareza do que se trata na leitura do código. utilizar um nome mais descritivo para a variável

2023-10-13 19:01 UTC, alan-rocha-newrizon commented on src/exercicio-3.ts
> +  let scientistToUpdate: Scientist | undefined = list.find(s => s.id === id);
variável com nome `s` não traz clareza do que se trata na leitura do código. utilizar um nome mais descritivo para a variável

2023-10-14 08:03 UTC, Ricardonovais1 commented on src/exercicio-3-commits.ts
> +function getCommitsGihubApi() {
Corrigido

2023-10-14 08:03 UTC, Ricardonovais1 commented on src/exercicio-3-commits.ts
> +function printCommit(commit: GithubCommit, count: number) {
Corrigido

2023-10-14 08:03 UTC, Ricardonovais1 commented on src/exercicio-3.ts
> +  let scientist: Scientist | undefined = list.find(s => s.id === id);
Corrigido

2023-10-14 08:06 UTC, Ricardonovais1 commented on src/exercicio-3.ts
> +  let scientistToUpdate: Scientist | undefined = list.find(s => s.id === id);
Corrigido

2023-10-14 08:06 UTC, Ricardonovais1 commented on src/exercicio-3.ts
> +  let scientist: Scientist | undefined = list.find(s => s.id === id);
Corrigido

2023-10-14 08:06 UTC, Ricardonovais1 commented on src/exercicio-3.ts
> +  let scientist: Scientist | undefined = list.find(s => s.id === id);
Corrigido

2023-10-14 08:06 UTC, Ricardonovais1 commented on src/exercicio-3.ts
> +  let scientist: Scientist | undefined = list.find(s => s.id === id);
Corrigido

2023-10-14 08:06 UTC, Ricardonovais1 commented on src/exercicio-3-commits.ts
> +function printCommit(commit: GithubCommit, count: number) {
Corrigido

2023-10-14 11:52 UTC, alan-rocha-newrizon approved these changes

2023-10-14 14:13 UTC, merged